### PR TITLE
Rename tools to show they are compatible with PySide2 and allow insta…

### PR DESCRIPTION
**Pull request by f3nix**
…llation parallel to PySide1 tools.

It fixes: https://github.com/PySide/pyside2/issues/82

### CODE REVIEW

**Comment by thopiekar** [comment]
Great! Any tools used to test your changes? Travis, etc?
You know I can trust your work, but having a message somewhere, that says that everything is great, is even better ^^

**Comment by thopiekar** [comment]
Btw. regards and have a nice weekend :smile:

**Comment by f3nix** [comment]
Hi,
here they are:
Travis log: https://travis-ci.org/f3nix/pyside2-setup/builds/123612354
AppVeyour log: https://ci.appveyor.com/project/f3nix/pyside2-setup

But the real test will be after you create a pyside2-tools package in your PPA :D

Have a nice weekend too! :)

Cheers,
Mateusz

**Comment by thopiekar** [comment]
Oh, yes, I still didn't make any package for it!
I should change that!

Thank you for the logs 😉

**Comment by f3nix** [comment]
Thanks! :)

**Comment by thopiekar** [comment]
Added ```pyside2-tools```. It includes the old changes but the next nightly tomorrow will include your changes :wink: 

Good night!

**Comment by f3nix** [comment]
Great! :) Thank you very much. Really appreciate it!
As a side note the pyside-setup submodule should be updated to point to latest commit but only after merging #5

**Comment by thopiekar** [comment]
Yes, I also had to do this here locally as debhelper builds the sources
out-of-tree 😉

**Comment by thopiekar** [comment]
Just a note:

The content of pyside2-tools is currently:
```
/.
/usr
/usr/bin
/usr/bin/pyside2-lupdate
/usr/bin/pyside2-rcc
/usr/bin/pyside2-uic
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/pyside2uic
/usr/lib/python3/dist-packages/pyside2uic/Compiler
/usr/lib/python3/dist-packages/pyside2uic/Compiler/__init__.py
/usr/lib/python3/dist-packages/pyside2uic/Compiler/compiler.py
/usr/lib/python3/dist-packages/pyside2uic/Compiler/indenter.py
/usr/lib/python3/dist-packages/pyside2uic/Compiler/misc.py
/usr/lib/python3/dist-packages/pyside2uic/Compiler/proxy_type.py
/usr/lib/python3/dist-packages/pyside2uic/Compiler/qobjectcreator.py
/usr/lib/python3/dist-packages/pyside2uic/Compiler/qtproxies.py
/usr/lib/python3/dist-packages/pyside2uic/__init__.py
/usr/lib/python3/dist-packages/pyside2uic/driver.py
/usr/lib/python3/dist-packages/pyside2uic/exceptions.py
/usr/lib/python3/dist-packages/pyside2uic/icon_cache.py
/usr/lib/python3/dist-packages/pyside2uic/objcreator.py
/usr/lib/python3/dist-packages/pyside2uic/port_v2
/usr/lib/python3/dist-packages/pyside2uic/port_v2/__init__.py
/usr/lib/python3/dist-packages/pyside2uic/port_v2/as_string.py
/usr/lib/python3/dist-packages/pyside2uic/port_v2/ascii_upper.py
/usr/lib/python3/dist-packages/pyside2uic/port_v2/invoke.py
/usr/lib/python3/dist-packages/pyside2uic/port_v2/load_plugin.py
/usr/lib/python3/dist-packages/pyside2uic/port_v2/proxy_base.py
/usr/lib/python3/dist-packages/pyside2uic/port_v2/string_io.py
/usr/lib/python3/dist-packages/pyside2uic/port_v3
/usr/lib/python3/dist-packages/pyside2uic/port_v3/__init__.py
/usr/lib/python3/dist-packages/pyside2uic/port_v3/as_string.py
/usr/lib/python3/dist-packages/pyside2uic/port_v3/ascii_upper.py
/usr/lib/python3/dist-packages/pyside2uic/port_v3/invoke.py
/usr/lib/python3/dist-packages/pyside2uic/port_v3/load_plugin.py
/usr/lib/python3/dist-packages/pyside2uic/port_v3/proxy_base.py
/usr/lib/python3/dist-packages/pyside2uic/port_v3/string_io.py
/usr/lib/python3/dist-packages/pyside2uic/properties.py
/usr/lib/python3/dist-packages/pyside2uic/pyside2-uic.1
/usr/lib/python3/dist-packages/pyside2uic/uiparser.py
/usr/lib/python3/dist-packages/pyside2uic/widget-plugins
/usr/lib/python3/dist-packages/pyside2uic/widget-plugins/qtdeclarative.py
/usr/lib/python3/dist-packages/pyside2uic/widget-plugins/qtwebkit.py
/usr/share
/usr/share/doc
/usr/share/doc/pyside2-tools
/usr/share/doc/pyside2-tools/changelog.Debian.gz
/usr/share/doc/pyside2-tools/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/pyside2-lupdate.1.gz
/usr/share/man/man1/pyside2-rcc.1.gz
/usr/share/man/man1/pyside2-uic.1.gz
```

What is ```/usr/lib/python3/dist-packages/pyside2uic/pyside2-uic.1?
It doesn't seem to be a module. Has it been installed to the correct place?

**Comment by f3nix** [comment]
It is a man file. It shouldn't be there.

**Pull request merged**
