### PR TITLE
Really fix the install target.

### PR DESCRIPTION
**Pull request by f3nix**
Left wrong path before... :/

### CODE REVIEW

**Comment by thopiekar** [comment]
Do you think it is really correct? While looking at the INSTALL instructions the CMake script expects the generated ```__init__.py``` at the binary directory. You are generating it into the source directory and the INSTALL command still expects it at the BINARY dir. I wonder how that should work.
But I agree that I should better generate it into ```${CMAKE_CURRENT_BINARY_DIR}/pyside2uic/__init__.py```.

```
GIT/PySide2/pyside2-tools$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b70f5c5..5038347 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -10,7 +10,7 @@ set(pyside2_tools_MINOR_VERSION "0")
 set(pyside2_tools_MICRO_VERSION "0")
 set(pyside2_tools_VERSION "${pyside2_tools_MAJOR_VERSION}.${pyside2_tools_MINOR_VERSION}.${pyside2_tools_MICRO_VERSION}")
 
-configure_file("pyside2uic/__init__.py.in" "pyside2uic/__init__.py" @ONLY)
+configure_file("pyside2uic/__init__.py.in" "${CMAKE_CURRENT_BINARY_DIR}/__init__.py" @ONLY)
 
 option(BUILD_TESTS "Build tests." TRUE)
 
```

**Comment by thopiekar** [comment]
I uploaded the my correction now. Thank you anyway :+1:

**Comment by f3nix** [comment]
Hi!
This PR reverted the changes I've made during renaming (I have made a mistake).

This is how it looked like before:
https://github.com/PySide/pyside2-tools/blob/42fe80bc55413bbf109ea76a7d511be7a7eeb23a/CMakeLists.txt

Line 13.

So it generated the file to the binary dir without a subdirectory. Your fix works too. Thanks! :)

Cheers,
Mateusz

**Comment by thopiekar** [comment]
No problem. At least the file gets generated at the correct place now :smile:

**Pull request closed without merging**
